# Generated by Django 3.1.5 on 2021-05-22 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='YouTubeVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('description', models.CharField(max_length=100000)),
                ('published_date', models.DateTimeField()),
                ('thumbnail_url', models.URLField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='YouTubeVideoLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('youtube_video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='youtube.youtubevideo')),
            ],
        ),
    ]
